#:include kv/home.kv
#:include kv/login.kv
#:include kv/events.kv
#:include kv/get_started.kv
#:include kv/signup.kv

ScreenManager:
    GetStartedScreen:
        name: 'get_started'
    SignUpScreen:
        name: 'signup'
    LoginScreen:
        name: 'login'
    HomeScreen:
        name: 'home'
    EventListScreen:
        name: 'event_list'
    EventDetailScreen:
        name: 'event_detail'
